import { AllPostData } from '../typings/post';

export const postData: AllPostData[] = [
       // "전체 게시글 조회" 데이터
        {
        id: 1,
        title: '제주 여행 후기 🍊',
        content: '제주도 여행 후기입니다.',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 44,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 2,
        title: '3박 4일 도쿄 여행 후기',
        content: '첫 도쿄 여행 다녀왔어요!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 20,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 3,
        title: '부산 여행 🌊',
        content: '해운대에서 즐거운 시간 보냈어요!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 30,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 4,
        title: '여수 밤바다 여행',
        content: '여수 밤바다 다녀왔습니다~!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 35,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 5,
        title: '서울 여행',
        content: '서울 여행 후기입니다.',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 43,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 6,
        title: '상하이 여행',
        content: '상하이 여행 후기!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 22,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 7,
        title: '후쿠오카 여행',
        content: '후쿠오카 여행 다녀왔어요!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 35,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 8,
        title: '런던 여행',
        content: '런던 여행 후기입니다.',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 41,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 9,
        title: '경주 여행 ',
        content: '안녕하세요, 이번에는 경주 다녀왔어요!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 31,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',    
        commentCount: 2,
    },
    {
        id: 10,
        title: '강릉 여행 🌊',
        content: '바다 풍경이 아름다운 강릉 여행 후기',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 26,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',   
        commentCount: 2,
    },
    {
        id: 11,
        title: '제주 여행 후기 🍊',
        content: '제주도 여행 후기입니다.',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 10,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 12,
        title: '3박 4일 도쿄 여행 후기',
        content: '첫 도쿄 여행 다녀왔어요!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 20,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 13,
        title: '부산 여행 🌊',
        content: '해운대에서 즐거운 시간 보냈어요!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 50,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 14,
        title: '여수 밤바다 여행',
        content: '여수 밤바다 다녀왔습니다~!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 35,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 15,
        title: '서울 여행',
        content: '서울 여행 후기입니다.',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 42,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 16,
        title: '상하이 여행',
        content: '상하이 여행 후기!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 22,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 17,
        title: '후쿠오카 여행',
        content: '후쿠오카 여행 다녀왔어요!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 35,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 18,
        title: '런던 여행',
        content: '런던 여행 후기입니다.런던 여행 후기입니다.런던 여행 후기입니다.런던 여행 후기입니다.런던 여행 후기입니다.',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 45,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    },
    {
        id: 19,
        title: '경주 여행 ',
        content: '안녕하세요, 이번에는 경주 다녀왔어요!',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 31,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01', 
        commentCount: 2,
    },
    {
        id: 20,
        title: '강릉 여행 🌊',
        content: '바다 풍경이 아름다운 강릉 여행 후기',
        imageUrl: 'https://picsum.photos/550/150',
        likes: 26,
        nickname: '김코딩',
        views: 100,
        createdAt: '2021-09-01',
        commentCount: 2,
    }

];