import { AllPostData } from '../typings/post'
export const postData: AllPostData[] = [

       // "전체 게시글 조회" 데이터
        {
        id: 1,
        title: '제주 여행 후기 🍊',
        content: '제주도 여행 후기입니다. 저는 지난 주에 제주도 여행을 다녀왔어요! 맛있는 음식도 많이 먹고 정말 행복했던 제주여행이었는데요 제주여행 시에 이색 디저트로 즐겨도 좋고, 그리고 제주여행 기념선물로도 정말 좋은 제라헌 크림떡 후기를 가',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 44,
        category: '제주도',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2024-12-01',
        replies: 2,
    },
    {
        id: 2,
        title: '3박 4일 도쿄 여행 후기',
        content: '첫 도쿄 여행 다녀왔어요!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 20,
        category: '자유',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2024-11-27',
        replies: 2,
    },
    {
        id: 3,
        title: '부산 여행 🌊',
        content: '해운대에서 즐거운 시간 보냈어요!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 30,
        category: '부산',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 4,
        title: '여수 밤바다 여행',
        content: '여수 밤바다 다녀왔습니다~!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 35,
        category: '리뷰',
        rating: 4,
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2023-09-01',
        replies: 2,
    },
    {
        id: 5,
        title: '충청남도 여행',
        content: '충청남도 여행 후기입니다.',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 43,
        category: '충청남도',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 6,
        title: '상하이 여행',
        content: '상하이 여행 후기!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 22,
        category: '자유',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 7,
        title: '후쿠오카 여행',
        content: '후쿠오카 여행 다녀왔어요!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 35,
        category: '자유',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 8,
        title: '런던 여행',
        content: '런던 여행 후기입니다.',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 41,
        category: '자유',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 9,
        title: '경주 여행 ',
        content: '안녕하세요, 이번에는 경주 다녀왔어요!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 31,
        category: '자유',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-07-15',    
        replies: 2,
    },
    {
        id: 10,
        title: '강릉 여행 🌊',
        content: '바다 풍경이 아름다운 강릉 여행 후기',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 26,
        category: '강원도',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-07-15',   
        replies: 2,
    },
    {
        id: 11,
        title: '제주 여행 후기 🍊',
        content: '제주도 여행 후기입니다.',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 10,
        category: '제주도',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-07-15',
        replies: 2,
    },
    {
        id: 12,
        title: '3박 4일 도쿄 여행 후기',
        content: '첫 도쿄 여행 다녀왔어요!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 20,
        category: '리뷰',
        rating: 5,
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 13,
        title: '부산 여행 🌊',
        content: '해운대에서 즐거운 시간 보냈어요! 부산 여행 놀거리로 좋은 송도해상케이블카를 타고 왔습니다. 부산 바다에서 케이블카를 타는 건 처음입니다. 결론부터 말하자면 후회 없이 즐거웠던 경험입니다. 솔직 후기 리뷰를... 위치 = 부산 서구 송도해변로 171 영업시간 09:00~21:00 전화번호 = ***-***-**** #부산여행 #부산여행코스',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 50,
        category: '자유',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 14,
        title: '여수 밤바다 여행',
        content: '여수 밤바다 다녀왔습니다~!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 35,
        category: '전라남도',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-04',
        replies: 2,
    },
    {
        id: 15,
        title: '서울 여행',
        content: '서울 여행 후기입니다.',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 42,
        category: '자유',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-05',
        replies: 2,
    },
    {
        id: 16,
        title: '경상남도 여행',
        content: '경상남도 여행 후기!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 22,
        category: '경상남도',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-11-10',
        replies: 2,
    },
    {
        id: 17,
        title: '광주 여행',
        content: '광주 여행 다녀왔어요!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 35,
        category: '광주',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 18,
        title: '충청북도 여행',
        content: '충청북도 여행 후기입니다. 그럼 다녀온 후기 바로 시작할게요 충청북도 근교 여행 : 세븐시스터즈 당일 투어 런던에 살고 있는 친구가 세븐시스터즈가 죽기전에 꼭 가봐야할 명소라고 추천 해줘서 일정 넉넉하게 갔던 만큼 당일투어로 다녀오기로 ',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 45,
        category: '충청북도',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 19,
        title: '경주 여행 ',
        content: '안녕하세요, 이번에는 경주 다녀왔어요!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 31,
        category: '경상북도',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01', 
        replies: 2,
    },
    {
        id: 20,
        title: '강릉 여행 🌊',
        content: '바다 풍경이 아름다운 강릉 여행 후기',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 26,
        category: '자유',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 21,
        title: '세종 여행 후기',
        content: '세종 여행 후기',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 26,
        category: '세종',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 22,
        title: '대전 빵투어',
        content: '대전 빵투어 하고 왔어요!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 26,
        category: '대전',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2023-09-01',
        replies: 2,
    },
    {
        id: 23,
        title: '울산 여행 🌊',
        content: '울산 여행 후기',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 26,
        category: '울산',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 24,
        title: '인천 여행 🌊',
        content: '인천 서해 구경하고 왔어요!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 26,
        category: '인천',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 25,
        title: '경기도 여행',
        content: '경기도 가서 맛집투어 하고 왔어요!',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 26,
        category: '경기도',
        author: {
        username: '김코딩',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 100,
        postedAt: '2021-09-01',
        replies: 2,
    },
    {
        id: 26,
        title: '(필독) 공지사항',
        content: '안녕하세요. 전체 공지사항 안내 드립니다.',
        photoUrl: 'https://picsum.photos/1100/200',
        likes: 30,
        category: '공지',
        author: {
        username: '관리자',
        profileUrl: 'https://picsum.photos/1100/200',
        },
        views: 300,
        postedAt: '2024-11-27',
        replies: 10,
    }

];

